import Head from "next/head";
import Navbar from "@/components/organisms/Navbar";
import Banner from "@/components/organisms/Banner";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="relative rounded-br-xl rounded-bl-xl overflow-hidden ">
        <Navbar />
        <Banner />
      </header>
      <main id="maincontent">
        <section>
          <h1 className="text-center">Destinasi Tempat Terbaik</h1>
        </section>
      </main>
    </>
  );
}
