import Head from "next/head";
import Navbar from "@/components/organisms/Navbar";
import Banner from "@/components/organisms/Banner";
import Destination from "@/components/organisms/Destination";
import Features from "@/components/organisms/Features";
import Gallery from "@/components/organisms/Gallery";
import Subscribe from "@/components/organisms/Subscribe";
import Footer from "@/components/organisms/Footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="relative  ">
        <Navbar />
        <Banner />
      </header>
      <main id="maincontent">
        <Destination />
        <Features />
        <Gallery />
        <Subscribe />
        <Footer />
      </main>
    </>
  );
}
